### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Dylan-DPC** [FaultyBean/laravel-firefly#147]
Languages offered: 

- [x] English
- [ ] French
- [x] German
- [ ] Dutch
- [ ] Italian
- [ ] Chinese 
- [x] Korean
- [ ] Japanese
- [ ] Hindi
- [x] Spanish
- [ ] Russian
- [ ] Swedish

**Comment by Dylan-DPC** [comment]
#142 #144

**Comment by AndreasElia** [comment]
I would also like a "Pirate" translation 😜

**Comment by deleugpn** [comment]
Where is Portuguese Brazillian?

**Comment by Dylan-DPC** [comment]
@deleugpn how different will the translations be from Portuguese?

**Comment by AndreasElia** [comment]
The current translations will also need cleaning up for plural/singular seperated by pipe rather than seperate array values.

**Comment by equero** [comment]
Spanish translation is finished for the available files  @Dylan-DPC
